name: YOHAN PREDICTION BOT

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Vérifier le token
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          if [ -z "$TELEGRAM_TOKEN" ]; then
            echo "❌ TELEGRAM_TOKEN est manquant"
            exit 1
          fi
          echo "✅ TELEGRAM_TOKEN est présent"

      - name: Lancer le bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot.py
